[package]
name = "terminal-arcade"
version = "0.0.1"
authors = ["Ramen Developer <ramendev2009@gmail.com>"]
edition = "2021"
description = "Terminal-based arcade-style games for when you're bored out of your mind."
readme = "README.md"
repository = "https://github.com/developer-ramen/terminal-arcade"
license = "MIT"
keywords = ["arcade", "terminal", "games"]
categories = ["games"]

[dependencies]
